build: Refactor axel building
Signed-off-by: nixxholas <nixholas@icloud.com>

diff --git a/build b/build
--- a/build
+++ b/build
@@ -295,19 +295,19 @@ function build_binaries() {
     PREBUILTS_BIN=${ROOT}/prebuilts/bin
     mkdir -p sources
 
-    if [[ ! -f ${PREBUILTS_BIN}/axel ]]; then
-        AXEL=${ROOT}/sources/axel
-        [[ ! -d ${AXEL} ]] && git -C "$(dirname "${AXEL}")" clone --depth=1 https://github.com/axel-download-accelerator/axel
-        git -C "${AXEL}" clean -fxdq
-        git -C "${AXEL}" pull
-        (
-            cd "${AXEL}" || die "Issue with cloning axel source!"
-            ./autogen.sh
-            ./configure --prefix="$(dirname "${PREBUILTS_BIN}")"
-            make ${JOBS} || die "Error building axel!"
-            make ${JOBS} install || die "Error installing axel!"
-        )
-    fi
+    #if [[ ! -f ${PREBUILTS_BIN}/axel ]]; then
+    #    AXEL=${ROOT}/sources/axel
+    #    [[ ! -d ${AXEL} ]] && git -C "$(dirname "${AXEL}")" clone --depth=1 https://github.com/axel-download-accelerator/axel
+    #    git -C "${AXEL}" clean -fxdq
+    #    git -C "${AXEL}" pull
+    #    (
+    #        cd "${AXEL}" || die "Issue with cloning axel source!"
+    #        ./autogen.sh
+    #        ./configure --prefix="$(dirname "${PREBUILTS_BIN}")"
+    #        make ${JOBS} || die "Error building axel!"
+    #        make ${JOBS} install || die "Error installing axel!"
+    #    )
+    #fi
 
     if [[ ! -f ${PREBUILTS_BIN}/pigz ]]; then
         PIGZ=${ROOT}/sources/pigz
